# --- Datenbank ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Hibernate / JPA ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate   # nur 'update' wenn Tabellen automatisch erstellt werden sollen
spring.jpa.show-sql=true

# --- Server ---
server.port=8080