# Datenbank
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.sslmode=require

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=${PORT:8080}

# Logging / Fehlerdebugging
logging.level.org.springframework.web=DEBUG
logging.level.com.booking.reportservice=DEBUG
server.error.include-message=always
server.error.include-stacktrace=always

supabase.anon.key=${SUPABASE_ANON_KEY}